# This is a basic workflow to help you get started with Actions

name: Upload Test

on:
  push:
    branches: [ test1-ga ]
  pull_request:
    branches: [ test1-ga ]

  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tests:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: mkdir -p testdir
      - run: echo hello > ./testdir/world.txt

      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./testdir/world.txt
